import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'sonner';
import NavBar from "../components/NavBar";
import Providers from "./providers";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme/theme';
import Provider from "../components/ProviderSession";
import { Roboto } from "next/font/google";


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // يمكنك إضافة أوزان أخرى مثل "300", "500", إلخ
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Health Ai+ ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className='bg-gray-200 dark:bg-sky-950'>
        <Toaster/>
        <Provider>
           <AppRouterCacheProvider>
          <Providers>
            <ThemeProvider theme={theme}>
                <NavBar />
                {children}
            </ThemeProvider>
          </Providers>
        </AppRouterCacheProvider>
        </Provider>
       
      </body>
    </html>
  );
}
